[0m11:09:54.908596 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b260b80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10cd05ee0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10cd05220>]}


============================== 11:09:54.917457 | e61211cd-cbc6-4a7f-b9bd-82ac52ca3e47 ==============================
[0m11:09:54.917457 [info ] [MainThread]: Running with dbt=1.8.5
[0m11:09:54.918879 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/villy/PycharmProjects/Payroll-Data-Integration-Platform/dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run --profiles-dir /Users/villy/PycharmProjects/Payroll-Data-Integration-Platform/dbt', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:09:54.920116 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/villy/PycharmProjects/Payroll-Data-Integration-Platform/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:09:54.922569 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.1363774, "process_user_time": 2.591068, "process_kernel_time": 0.41229, "process_mem_max_rss": "85655552", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m11:09:54.925341 [debug] [MainThread]: Command `dbt run` failed at 11:09:54.924984 after 0.14 seconds
[0m11:09:54.927785 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b260b80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10cd05730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10cd05520>]}
[0m11:09:54.928809 [debug] [MainThread]: Flushing usage events
[0m11:29:30.428858 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104160ac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105c04df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105c04fd0>]}


============================== 11:29:30.436397 | 0a31fd16-b6de-4bba-9be4-ce334e09e963 ==============================
[0m11:29:30.436397 [info ] [MainThread]: Running with dbt=1.8.5
[0m11:29:30.437835 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/villy/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:29:30.439054 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/villy/PycharmProjects/Payroll-Data-Integration-Platform/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:29:30.441349 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.13238859, "process_user_time": 2.237572, "process_kernel_time": 0.246272, "process_mem_max_rss": "85311488", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m11:29:30.443953 [debug] [MainThread]: Command `dbt run` failed at 11:29:30.443225 after 0.13 seconds
[0m11:29:30.445833 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104160ac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105c04580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105c043a0>]}
[0m11:29:30.446833 [debug] [MainThread]: Flushing usage events
